## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.6.4
  - 0.7
  - nightly
notifications:
  email: false
git:
  depth: 99999999

## allow failures (tests will run but not make your overall status red)
matrix:
  allow_failures:
    - julia: nightly

## uncomment and modify the following lines to manually install system packages
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

## uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("LazySets"); Pkg.test("LazySets"; coverage=true)'
after_success:
  - julia -e 'Pkg.add("Documenter");'
  - julia -e 'cd(Pkg.dir("BernsteinExpansions")); include(joinpath("docs", "make.jl"))'
  - julia -e 'Pkg.add("Coverage")'
  - julia -e 'cd(Pkg.dir("BernsteinExpansions")); using Coverage; Codecov.submit(Codecov.process_folder())'
